from nanocalibur.dsl_markers import CodeBlock


CodeBlock.begin("starcraft_clone_constants")
"""Gameplay constants, costs, and fixed world coordinates for the 1v1 map."""

TILE = 16
MAP_COLS = 128
MAP_ROWS = 72

BM_SOLID = 1
BM_WALL = 2
BM_NONE = 0

START_MINERALS = 300
START_GAS = 0
START_SUPPLY_USED = 2
START_SUPPLY_CAP = 10
SUPPLY_DEPOT_BONUS = 8

MAX_POOL_PER_UNIT = 10
INITIAL_ACTIVE_WORKERS = 2

# Buildings (minerals, gas)
COST_SUPPLY_M = 100
COST_SUPPLY_G = 0
COST_BARRACKS_M = 150
COST_BARRACKS_G = 0
COST_REFINERY_M = 75
COST_REFINERY_G = 0
COST_FACTORY_M = 200
COST_FACTORY_G = 100
COST_LAB_M = 150
COST_LAB_G = 150

# Units (minerals, gas, supply)
COST_WORKER_M = 50
COST_WORKER_G = 0
SUPPLY_WORKER = 1

COST_MARINE_M = 50
COST_MARINE_G = 0
SUPPLY_MARINE = 1

COST_MARAUDER_M = 100
COST_MARAUDER_G = 25
SUPPLY_MARAUDER = 2

COST_MEDIC_M = 50
COST_MEDIC_G = 25
SUPPLY_MEDIC = 1

COST_TANK_M = 150
COST_TANK_G = 125
SUPPLY_TANK = 3

COST_SCOUT_M = 100
COST_SCOUT_G = 150
SUPPLY_SCOUT = 2

# Upgrades
COST_UPGRADE_ATTACK_M = 100
COST_UPGRADE_ATTACK_G = 100
COST_UPGRADE_ARMOR_M = 100
COST_UPGRADE_ARMOR_G = 100

# Unit stats
WORKER_HP = 60
WORKER_ATTACK = 4
WORKER_ARMOR = 0
WORKER_SPEED = 90
WORKER_GATHER = 2
WORKER_CARGO_CAP = 8
CAMERA_PAN_SPEED = 18

MARINE_HP = 45
MARINE_ATTACK = 6
MARINE_ARMOR = 0
MARINE_SPEED = 120

MARAUDER_HP = 120
MARAUDER_ATTACK = 10
MARAUDER_ARMOR = 1
MARAUDER_SPEED = 90

MEDIC_HP = 60
MEDIC_ATTACK = 0
MEDIC_ARMOR = 0
MEDIC_SPEED = 105
MEDIC_HEAL = 2

TANK_HP = 170
TANK_ATTACK = 18
TANK_ARMOR = 1
TANK_SPEED = 70

SCOUT_HP = 100
SCOUT_ATTACK = 14
SCOUT_ARMOR = 0
SCOUT_SPEED = 150

# Building stats
HQ_HP = 2000
SUPPLY_DEPOT_HP = 500
BARRACKS_HP = 1000
REFINERY_HP = 800
FACTORY_HP = 1250
LAB_HP = 900

# Resources
RESOURCE_AMOUNT = 50_000
RESOURCE_PER_TICK = 2

# Production times (ticks at game tick-rate)
BUILD_TIME_SUPPLY = 90
BUILD_TIME_BARRACKS = 120
BUILD_TIME_REFINERY = 90
BUILD_TIME_FACTORY = 140
BUILD_TIME_LAB = 120

TRAIN_TIME_WORKER = 45
TRAIN_TIME_MARINE = 35
TRAIN_TIME_MARAUDER = 55
TRAIN_TIME_MEDIC = 50
TRAIN_TIME_TANK = 85
TRAIN_TIME_SCOUT = 80

UPGRADE_TIME_ATTACK = 120
UPGRADE_TIME_ARMOR = 120

# World coordinates
P1_BASE_X = 14 * TILE
P1_BASE_Y = (MAP_ROWS // 2) * TILE
P2_BASE_X = (MAP_COLS - 14) * TILE
P2_BASE_Y = (MAP_ROWS // 2) * TILE

P1_SUPPLY_X = P1_BASE_X + 5 * TILE
P1_SUPPLY_Y = P1_BASE_Y - 4 * TILE
P1_BARRACKS_X = P1_BASE_X + 5 * TILE
P1_BARRACKS_Y = P1_BASE_Y
P1_REFINERY_X = P1_BASE_X + 5 * TILE
P1_REFINERY_Y = P1_BASE_Y + 4 * TILE
P1_FACTORY_X = P1_BASE_X + 10 * TILE
P1_FACTORY_Y = P1_BASE_Y - 2 * TILE
P1_LAB_X = P1_BASE_X + 10 * TILE
P1_LAB_Y = P1_BASE_Y + 2 * TILE

P2_SUPPLY_X = P2_BASE_X - 5 * TILE
P2_SUPPLY_Y = P2_BASE_Y - 4 * TILE
P2_BARRACKS_X = P2_BASE_X - 5 * TILE
P2_BARRACKS_Y = P2_BASE_Y
P2_REFINERY_X = P2_BASE_X - 5 * TILE
P2_REFINERY_Y = P2_BASE_Y + 4 * TILE
P2_FACTORY_X = P2_BASE_X - 10 * TILE
P2_FACTORY_Y = P2_BASE_Y - 2 * TILE
P2_LAB_X = P2_BASE_X - 10 * TILE
P2_LAB_Y = P2_BASE_Y + 2 * TILE

P1_MINERAL_X = P1_BASE_X + 4 * TILE
P1_MINERAL_Y = P1_BASE_Y - 10 * TILE
P1_GAS_X = P1_BASE_X + 4 * TILE
P1_GAS_Y = P1_BASE_Y + 10 * TILE

P2_MINERAL_X = P2_BASE_X - 4 * TILE
P2_MINERAL_Y = P2_BASE_Y - 10 * TILE
P2_GAS_X = P2_BASE_X - 4 * TILE
P2_GAS_Y = P2_BASE_Y + 10 * TILE

P1_RALLY_X = P1_BASE_X + 14 * TILE
P1_RALLY_Y = P1_BASE_Y
P2_RALLY_X = P2_BASE_X - 14 * TILE
P2_RALLY_Y = P2_BASE_Y

CodeBlock.end("starcraft_clone_constants")
